// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAveuo3IwywPKl6A8VJgwyFhcc2hIeSJa4',
    appId: '1:612804954817:web:0f7359b9015acb0f18e240',
    messagingSenderId: '612804954817',
    projectId: 'mynotesflutter-2026',
    authDomain: 'mynotesflutter-2026.firebaseapp.com',
    storageBucket: 'mynotesflutter-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiF0nydh9Gn7rtbXEc38JmAXtCCcDmcJU',
    appId: '1:612804954817:android:f0d5dd835db55d9018e240',
    messagingSenderId: '612804954817',
    projectId: 'mynotesflutter-2026',
    storageBucket: 'mynotesflutter-2026.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk7EqOTbca84tcIkaNKqbL92T0D0nZZ84',
    appId: '1:612804954817:ios:7f9679d15fbf392218e240',
    messagingSenderId: '612804954817',
    projectId: 'mynotesflutter-2026',
    storageBucket: 'mynotesflutter-2026.firebasestorage.app',
    iosBundleId: 'com.gird.mynotesflutter',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk7EqOTbca84tcIkaNKqbL92T0D0nZZ84',
    appId: '1:612804954817:ios:7f9679d15fbf392218e240',
    messagingSenderId: '612804954817',
    projectId: 'mynotesflutter-2026',
    storageBucket: 'mynotesflutter-2026.firebasestorage.app',
    iosBundleId: 'com.gird.mynotesflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAveuo3IwywPKl6A8VJgwyFhcc2hIeSJa4',
    appId: '1:612804954817:web:0b1748b6c660fc9a18e240',
    messagingSenderId: '612804954817',
    projectId: 'mynotesflutter-2026',
    authDomain: 'mynotesflutter-2026.firebaseapp.com',
    storageBucket: 'mynotesflutter-2026.firebasestorage.app',
  );
}
